# Generated by Django 3.2.7 on 2022-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='markdown',
            field=models.TextField(),
        ),
    ]
