# Generated by Django 3.2.7 on 2022-06-25 16:11

import articles.models
import articles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(storage=articles.storage.OverwriteStorage(), upload_to=articles.models.get_cover_image_path),
        ),
    ]
