# Generated by Django 3.2.7 on 2022-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default=None, upload_to='\x07uthor\\static\\images\x07vatars'),
        ),
    ]
