# Generated by Django 3.2.7 on 2022-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20220621_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last login'),
        ),
    ]
