# Generated by Django 3.2.7 on 2022-06-22 16:15

import authors.models
import authors.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default=authors.models.get_default_avatar, null=True, storage=authors.storage.OverwriteStorage(), upload_to=authors.models.get_avatar_image_path),
        ),
    ]
